### PR TITLE
Add a nix shell for building

### PR DESCRIPTION
**Pull request by googleson78**
I got to this after trying to build and approximating what different libs were failing on.

### CODE REVIEW

**Comment by Bodigrim** [comment]
@googleson78 I can merge this as is, but I don’t use Nix and would not be able to maintain this config.

**Comment by googleson78** [comment]
Similarly, I probably won't be building `clc-stackage` often enough to keep this up-to-date actively. But it still could save future people time, and in the worst case in which it just doesn't work, it's not really time consuming to try.

How about adding a disclaimer that this is only an approximation and not actively maintained?

**Comment by Bodigrim** [comment]
Yes, please add a disclaimer.

**Comment by googleson78** [comment]
I added a `README.md` with a disclaimer in it, along with mentioning myself in the nix flake file.

**Comment by Bodigrim** [comment]
Thanks!

**Pull request merged**
