### PR TITLE
Generate package set on-the-fly

### PR DESCRIPTION
**Pull request by tbidne**
# Intro

Here's my implementation of the idea discussed [here](https://github.com/haskell/clc-stackage/pull/17#issuecomment-2350927482). The major change is that `clc-stackage` is now an executable that generates a stackage project on the fly, rather than a library with the dependencies hardcoded.

# Discussion

## Batching

This PR also implements the sequential batching behavior I mentioned. That is, if the user runs `clc-stackage --batch 20`, then the package set will be divided into groups of size 20, which will then be built sequentially.

If `--batch` is not specified, then the behavior is essentially the same as before: we will produce a single group that contains the entire set, and `--keep-going` is passed by default. The only difference, then, is the output. Rather than seeing the cabal output directly, it is redirected to the file `output/logs/current-build/stdout.log`, which is renamed `output/logs/<pkg_name>/stdout.log` after exiting.

## Testing

There are a couple test suites; the `functional` one actually runs `clc-stackage`, though it filters the packages down to 5 so that CI is manageable. This isn't really useful for testing the package upgrades (you'd still want to manually verify everything). But it can be useful when making changes to `clc-stackage` itself i.e. you should be able to rely on the tests to catch logic errors without having to start building everything yourself.

# Misc Notes

- The diff is pretty large! Apologies for that. The [dev.md](https://github.com/tbidne/clc-stackage/blob/on-the-fly/dev.md) doc contains an overview that is hopefully helpful. Also the code very much follows my style, so feel free to request style changes (or anything else). If there's anything I can do to make this easier to review, please let me know.

- Previously, the cabal.project's `constraints` sections had some `< 0` constraints, presumably to exclude certain packages. I don't believe this is necessary anymore, since [excluded_pkgs.json](https://github.com/tbidne/clc-stackage/blob/on-the-fly/excluded_pkgs.json) should take care of this. But let me know if you disagree.

- I have not gone through a full build yet, though I have built about half. I have manually confirmed that the generated package set is the same as the HEAD clc-stackage's `build-depends`.

- I expect there may be much to discuss / change, hence opening this now. But no rush! I need to verify the package set myself, and I'd like to benchmark different `--batch` values, though the latter could take quite some time.

### CODE REVIEW

**Comment by tbidne** [comment]
**Edit:** The below is now implemented in this PR.

---

It occurs to me that the `excluded_pkgs.txt` would be better as something structured, say, a json file. We could pretty easily support os-specific exclusions:

```json
{
  "all": [
    "<snip>"
  ],
  "linux": [
    "hfsevents"
  ],
  "osx": [
  ],
  "windows": [
    "hfsevents",
    "postgresql-libpq"
  ]
}
```

This is more robust than my current ad-hoc [method](https://github.com/tbidne/clc-stackage/blob/on-the-fly/src/builder/CLC/Stackage/Builder/Writer.hs#L74), and would also solve https://github.com/haskell/clc-stackage/issues/3.

```haskell
osPkgs :: [Text]
osPkgs = (pkgsIndent <>) <$>

#if OSX

  [ ", hfsevents ==0.1.6"
  ]

#else

  [
  ]

#endif
```

**Comment by Bodigrim** [comment]
This is awesome! Please ping when it's ready to be merged.

**Comment by tbidne** [comment]
@Bodigrim Ready for review / merge. Apart from the aforementioned changes, I also added the following libs:

- Added `postgresql-libpq` to linux and osx (Resolves https://github.com/haskell/clc-stackage/issues/3).
- Added `bindings-GLFW`. It was excluded in a commit (5acc631a20dd603af617ff0def1a0bddbe905120), but it's a transitive dep anyway, since we currently require `GLFW-b`. Moreover, we need to be explicit about `bindings-GLFW` since `GLFW-b` requires a tight bound, hence adding the dep back.

I have built everything myself, with the only failures being the usual nix problem-children (`sbv`, `grisette`).

**Comment by Bodigrim** [comment]
Awesome!

**Pull request merged**
