### PR TITLE
Update to GHC 9.8.2 (nightly-2024-03-26)

### PR DESCRIPTION
**Pull request by tbidne**
Thought I'd open this to get the ball rolling, though I understand if we want to wait until more packages are added.

### Dropped packages

With this PR the package count drops by about 200:

```
-- master
λ. grep == clc-stackage.cabal | wc -l
2876

-- this
λ. grep == clc-stackage.cabal | wc -l
2643
```

In particular, quite a few `amazonka` packages have dropped out, so perhaps we want to wait for [that to be fixed](https://github.com/commercialhaskell/stackage/issues/7261) before merging.

### New system dependencies

There are a couple new system dependencies:

- `openssl` (required by `core-telemetry`, `cql-io`)
- `primecount` (required by `primecount`)

### Excluded packages

Other than exes, of the new packages that appeared in this snapshot, I excluded:

- `cuda`: Requires proprietary CUDA deps.
- `stack`: Requires custom GHC to be on the PATH as it is used in TH. If this isn't considered too onerous I can add it.

## Nix

@googleson78 

There isn't too much that is new here, other than documenting why some system libs are needed.

The main change is having `nixpkgs.follows = "ghc_nix/nixpkgs"`. I did this since we need the custom GHC to be built with the same `glibc` as the system libs. Because [`ghc.nix`](https://github.com/alpmestan/ghc.nix) is a (the most?) popular way to build GHC with nix, it seems useful to make this relationship explicit. Case in point, I made this change after running into errors using a recent version of `nixos-unstable` here, as my `ghc.nix` built compiler was on an earlier `glibc.`

Note that `ghc.nix`'s current nixpkgs is fairly old (September 2023).

### CODE REVIEW

**Comment by Bodigrim** [comment]
Thanks @tbidne! I think re-adding `stack` is worth it. And let's wait a bit longer for `amazonka`.

**Comment by Bodigrim** [comment]
@tbidne could you please regenerate it with the latest nightly? I'd like to go ahead with it.

**Comment by tbidne** [comment]
Can do. Note the amazonka issue is still unresolved, though I suppose it probably makes more sense to update to GHC 9.8 now and update again later as necessary.

**Comment by Bodigrim** [comment]
Yeah, let's skip `amazonka` for now.

**Comment by tbidne** [comment]
@Bodigrim I updated the package set. I'm about 30% of the way through building it, and it looks like we took on a couple more system dependencies (`fftw` and `expat` so far). If you don't mind waiting a day or so, I should have enough cpu cycles by then to get through everything.

**Comment by Bodigrim** [comment]
Thanks for working on this, much appreciated!

**Comment by tbidne** [comment]
@Bodigrim Just finished. Everything built except for 3 packages: `grisette`, `hw-json-simd`, and `sbv`. I am confident these are nix problems (documented [here](https://github.com/Bodigrim/clc-stackage/pull/16/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R49)), so this can be merged AFAICT.

**Comment by Bodigrim** [comment]
Thanks a ton!

**Comment by tbidne** [comment]
Thanks for merging!

**Pull request merged**
